### ISSUE TITLE
Why it's much faster in XE7+ versions?

### ISSUE THREAD

**Issue by edwinyzh** [d-mozulyov/Rapid.Generics#2]
Hello,

Out of curiosity - why it's much faster in XE7+ versions? Because this library utilize the new features only available in XE7+ versions, or because the System.Generics inXE7**+** is implemented worse than XE7**-** systems?

**Comment by d-mozulyov** [comment]
Hello,

In XE7+ there are inline functions GetTypeKind, IsManagedType and HasWeakRef, which allow to execute type-specific code, such as inline hash function and comparer in TRapidDictionary, for example.
