### ISSUE TITLE
Nice classes,  and a problem is use iTask as a List item. Can not free or memory leak.

### ISSUE THREAD

**Issue by wqmeng** [d-mozulyov/Rapid.Generics#3]
Nice classes,  and a problem is use iTask as a List item. Can not free or memory leak.
Hello, 

Have you tried the iTask free?  I use a TList<iTask> to store the Tasks, and after my application terminate, I free the Tlist instance at the formClose procedure,  But it will raise a exception when the list free, after I cancel the tasks.  And if I leave the List not free, I will get a report for memory leak from FastMM4. 

And another suggestion is can you try to change the free or Destroy function of your classes to match the classes from EMB,  Today I changed my app to use the classes such as Tlist from EMB and have to change many code in my Destroy function as it report exception of access validate.  That means the Tlist will free subitems in many case, but yours Tlist will not and have to free a subitem by invoke the free method of the subitem.  Which cause it is very hard to switch from your classes to EMB Tlist and also reverse back. 

Please try the TList<iTask> and find what's wrong of your Tlist.  And fix the matter, 

I like your classes much as preferring to the performance enhancement.  But if you can get it compatible with the EMB classes when free the Tlist or others, it will be much better.

Thank you.

**Comment by wqmeng** [comment]
Here is some code when free the list. 

My app will complete the tasks before the application terminate,  It has other thread to check the complete status of a Task can will delete it from the TastList.  So mostly the TaskList will have nothing when the app is close,  but ever the count is 0,  TaskList.clear will raise exception of Free will. 

  try
    if Assigned(TaskList) then
    begin
      for i := TaskList.Count - 1 downto 0 do
      begin
        TaskList[i].Cancel;
//        TaskList[i] := nil;
      end;

      while TaskList.Count > 0 do
      begin
        Sleep(10);
      end;
      //TaskList.Clear;
      TaskList.Free;
      TaskList := nil;
    end;
  except

  end;

**Comment by wqmeng** [comment]
`TaskList: TList<ITask>;`

**Comment by d-mozulyov** [comment]
wqmeng, try to replace Rapid.Generics.TList<> to System.Generics.Collections.TList<>. Is there any memory leak?

**Comment by wqmeng** [comment]
Hi, 

The matter is when `TList<iTask>`, I have exception to clear or Free the List.  So that it finally get memory leak.  After replace the Rapid.Generics.TList, there is no exception when free the List, so it is no memory leak.

**Comment by wqmeng** [comment]
Hi, 
`Rapid.Generics.TList<iTask>`,  the List item is a interface is not a class, so that when you free the list, that you tried to invoke the free method of the iTask?   But why even the count of the list is 0,  to clear or free the list still get a exception.

**Comment by wqmeng** [comment]
`class procedure TRAIIHelper<T>.ClearArray(Items: P; Count: NativeUInt; Offset: NativeUInt);
var
  i: NativeUInt;
  Item: ^TRAIIHelper.TData16;
  {$ifdef SMARTGENERICS}
  VType: Integer;
  {$endif}
begin
  {$ifdef SMARTGENERICS}
  if (System.IsManagedType(T) or System.HasWeakRef(T)) then
  {$else}
  if (Assigned(FOptions.ClearProc)) then
  {$endif}
  begin
    if (Offset = 0) then Offset := SizeOf(T);
    Item := Pointer(Items);

    for i := 1 to Count do
    begin
      {$ifdef SMARTGENERICS}
      case GetTypeKind(T) of
        {$ifdef AUTOREFCOUNT}
        tkClass,
        {$endif}
        tkWString, tkLString, tkUString, tkInterface, tkDynArray:
        begin
          if (Item.Native <> 0) then
          case GetTypeKind(T) of
            {$ifdef AUTOREFCOUNT}
            tkClass:
            begin
              TRAIIHelper.RefObjClear(@Item.Native);
            end;
            {$endif}
            {$ifdef MSWINDOWS}
            tkWString:
            begin
              TRAIIHelper.WStrClear(@Item.Native);
            end;
            {$else}
            tkWString,
            {$endif}
            tkLString, tkUString:
            begin
              TRAIIHelper.ULStrClear(@Item.Native);
            end;
            tkInterface:
            begin
              IInterface(Item.Native)._Release;
            end;
            tkDynArray:
            begin
              TRAIIHelper.DynArrayClear(@Item.Native, TypeInfo(T));
            end;
          end;
        end;
        {$ifdef WEAKINSTREF}
        tkMethod:
        begin
          if (Item.Method.Data <> nil) then
            TRAIIHelper.WeakMethodClear(@Item.Method.Data);
        end;
        {$endif}
        tkVariant:
        begin
          VType := Item.VarData.VType;
          if (VType and TRAIIHelper.varDeepData <> 0) then
          case VType of
            varBoolean, varUnknown+1..varUInt64: ;
          else
            System.VarClear(Variant(Item.VarData));
          end;
        end;
      else
        FOptions.ClearProc(FOptions, Item);
      end;
      {$else}
      FOptions.ClearProc(FOptions, Item);
      {$endif}

      Inc(NativeUInt(Item), Offset);
    end;
  end;
end;`


Here is where the exception raise out.  
`IInterface(Item.Native)._Release;`

When I trace the value of the Item.Native， it shows the value is -71578188,  so that the interface is not valid?   Then we should check the Item.Native is valid before invoke the _Release method? 


Thank you.

**Comment by d-mozulyov** [comment]
Please, send me a simple project with `TList<Interface>` instance, where I'll repeat the bug

**Comment by d-mozulyov** [comment]
> `TaskList: TList<ITask>;`
Please, send me a simple project with TList<Interface> instance, where I'll repeat the bug

**Comment by d-mozulyov** [comment]
Unfortunately I did not get a test project, I hope the error was not in the library
But the library has been updated, I recommend to download the new version
