### ISSUE TITLE
very Great job ! but some things stranges in XE4... 

### ISSUE THREAD

**Issue by mpodvin** [d-mozulyov/Rapid.Generics#4]
I run your demos with ReportMemoryLeaksOnShutdown := true;
there's some memory leaks when exit application:
In dictionnaries :
![image](https://user-images.githubusercontent.com/11146591/43763419-fe51108c-9a2a-11e8-8401-b518a59040b2.png)
In sortings :
![image](https://user-images.githubusercontent.com/11146591/43763647-92883424-9a2b-11e8-8372-5dda47f4d3cc.png)

and this :
Very slow in dictionnaries (strange? no ?):
![image](https://user-images.githubusercontent.com/11146591/43763282-ae7aebbe-9a2a-11e8-95c3-dde5de3f0abe.png)

thanks for your time,
good job, very fast in XE4 too
Michel

**Comment by d-mozulyov** [comment]
> I run your demos with ReportMemoryLeaksOnShutdown := true;
> there's some memory leaks when exit application:

Fortunately, this is not a memory leak. This a feature of *.dpr reference function management.  
You may move the benchmark code to external function, for example:
```
procedure RUN;
begin
  with TRunner<string>.Create(...) do
  try
    RunEach;
  finally
    Free;
  end;

  with TRunner<Single>.Create(...) do
  try
    RunEach;
  finally
    Free;
  end;

  with TRunner<Integer>.Create(...) do
  try
    RunEach;
  finally
    Free;
  end;
end;

begin
  ReportMemoryLeaksOnShutdown := True;
  RUN;
end.
```

> Very slow in dictionnaries (strange? no ?):

Rapid,Generics hash functions differ from System.Generics functions. That is why they can be slowly in some cases, for example for Integer type. But we should understand, that the performance of searching is more important, than the performance of addition.
