### ISSUE TITLE
Strange FSize in TRAIIHelper

### ISSUE THREAD

**Issue by mpodvin** [d-mozulyov/Rapid.Generics#5]
It seems that there is a bug in TRAIIHelper :
![bugarraystatic](https://user-images.githubusercontent.com/11146591/45755371-8919a480-bc1e-11e8-8eb6-b77f9ae378aa.jpg)
800 bytes for an array of double with 10 'double' : 8*10=80 bytes ! No?
thanks a lot.

**Comment by Xor-el** [comment]
@mpodvin , that is not the proper way to create a Delphi object.
It should be 
`rec := TRAIIHelper<TDoubleArray>.Create;`

**Comment by mpodvin** [comment]
No Way! it's a record
because compiler error ! (rec := TRAIIHelper<`TDoubleArray`>.Create;)
here, it's the only way for my sample to show the bug!

**Comment by d-mozulyov** [comment]
Hello
Try this

```
type
  TDoubleArray = array[0..9] of Double;

procedure TForm2.Button1Click(Sender: TObject);
begin
  Caption := IntToStr(TRAIIHelper<TDoubleArray>.Options.Size);
end;

initilization
  TRAIIHelper<TDoubleArray>.Create;

end.
```

**Comment by mpodvin** [comment]
thanks!
But, it's the same thing...
![bugrapidsize](https://user-images.githubusercontent.com/11146591/45802158-486d6a00-bcb6-11e8-92e1-a5d30e93910c.jpg)
800 bytes for the array !?

and strange too for ItemSize :
![bugitemsizerapids](https://user-images.githubusercontent.com/11146591/45802195-62a74800-bcb6-11e8-8dc0-d74a57dcd4cc.jpg)
80 bytes for an item (a 'double' here)!

**Comment by d-mozulyov** [comment]
Fixed
Thank you!
