### ISSUE TITLE
Something is wrong with InterfaceDefaults.GetHashCode_N4

### ISSUE THREAD

**Issue by sglienke** [d-mozulyov/Rapid.Generics#6]
I looked into your comparers and found that some of them improve performance quite significantly.
However the hashcode for Integer seems to kinda weird - its values are very clustered and not evenly distributed. You can notice this with your own dictionaries benchmark in the SystemRapid test. It is significantly slower than SystemSystem.

**Comment by d-mozulyov** [comment]
sglienke, 

Many thanks for your attention to the project. 
Could you develop the same fast, but better hash functions?

**Comment by joachimmarder** [comment]
> Could you develop the same fast, but better hash functions?

You could try FNV 1a:
https://stackoverflow.com/questions/4191523/implementation-of-fnv
http://codeverge.com/embarcadero.delphi.general/fnv-1a-hash/1064108
